### ISSUE TITLE
Syntax error in game.js

### ISSUE THREAD

**Issue by dfyx** [rblopes/my-phaser-template#1]
I've just run your code with `npm start` and the produced `game.js` appears to contain a syntax error in line 5 (`define("app/objects/Preloader"`).

Opera complains about `Uncaught SyntaxError: Unexpected token {` while Firefox says `SyntaxError: missing ; before statement`. Sadly, both don't tell me the exact position of the syntax error.

**Comment by dfyx** [comment]
Okay, I just ran it through http://esprima.org/demo/validate.html and the part it complains about is `elseif("value" in desc && desc.writable){return desc.value;}` which appears to be automatically generated code (probably by 6to5)...

**Comment by rblopes** [comment]
Not quite a 6to5 issue, but seems like recent versions changed how output code is formatted when using the `compact` option, maybe that's broken, I don't know…

So try removing the `compact: true` line under `project-config.json`. I reproduced your issue here, and that solved the problem.

**Comment by dfyx** [comment]
Confirmed to be working for me.
